### PR TITLE
bump version

### PR DESCRIPTION
**Pull request by lolwhitaker**

### CODE REVIEW

**Comment by biesiad** [comment]
Ah.. right. Busy day. Thanks again :)

**Comment by lolwhitaker** [comment]
Thanks!  Can you publish the new version please?

**Comment by biesiad** [comment]
Done.

**Comment by lolwhitaker** [comment]
Thanks!

I had to restart my terminal to get 0.5.3 to be picked up in the executable correctly.  Running just:

``` bash
gem uninstall deelay
gem install deelay
deelay
```

It kept looking for version 0.5.2 for some reason?  After I restarted my mac terminal it started up.

**Pull request merged**
